[package]
name = "randomwalks-lib"
version = "0.1.0"
authors = ["Alexander Korn <alexander.korn@tu-dortmund.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
